modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/davidjjung/copperpot/issues"
license = "MIT License"

[[mods]]
    modId = "copperpot"
    version = "1.16.5-1.2.0"
    logoFile = "logo.png"
    itemIcon = "copperpot:baked_alaska_block"
    authors = "DavigJ"
    credits = "DavigJ for some code, GracefulLion for gradle/recipes and playtesting, splet, and dannyk11. Additional thanks to Nary for spritework, and a big thanks to vectorwing for the Farmer's Delight mod to begin with!"
    displayName = "Copper Pot"
    description = '''
An unofficial add-on for Farmer's Delight! Adds a copper pot for those stuck waiting on the iron age.
    '''

[[dependencies.copperpot]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.copperpot]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.copperpot]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.2.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.copperpot]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[0.4.2,)"
    ordering = "AFTER"
    side = "BOTH"